### ISSUE TITLE
X and Y joystick values of exactly zero may be ignored.

### ISSUE THREAD

**Issue by googolp** [Bumblefuck/HBR-Proportional-Valve#4]
There is a missing case where a `value` of zero will pass though all of the `if` conditions and the analog output will remain unchanged.

**Comment by queuetue** [comment]
Although this deserves some consideration (seeing as we're swinging steel around with man-crushing power), the only time you're likely to see a perfect zero with an analog control is when a ground wire breaks.  

This probably falls into a larger class of "error response" handling - ie, what we do when someone hits a "soft" error condition and how best to assume we're not killing anyone that can't reach the kill switch.

@Bumblefuck how much consideration do you want wrt not making human paste?

**Comment by Bumblefuck** [comment]
meh.
I'll make a sign.
;)

**Comment by googolp** [comment]
I agree that it is unlikely to read a true analog 0, but in this case it is a joystick position 0 that causes the error. A joystick position 0 is actually an ADC reading of 520 if I understand the code correctly.

**Comment by Bumblefuck** [comment]
But really, yes; excellent idea. I think that soft faults should just
trigger the e-stop loop. It would be nice to have a couple leds orange for
faults, red for e-stop. Later we could get the leds to blink at different
rates to indicate various fault conditions. But that's in the "later"
column.

**Comment by googolp** [comment]
@Bumblefuck 

The sign can read:
`DANGER DUE TO: off by one error`

**Comment by queuetue** [comment]
CAUTION: Human paste manufacturing area. Please wear squints.

**Comment by googolp** [comment]
Additional safety can be had by getting a joystick with dual wipers on each axis. If the wipers disagree by a certain margin an error condition can be asserted.

This might be overkill if the joystick is just for temporary prototyping purposes.

**Comment by Bumblefuck** [comment]
​​

**Comment by vector76** [comment]
Along the lines of emergency stop I might offer another idea: a second arduino that controls emergency shutdown (mini is super cheap).  Primary arduino could send a pulsed signal meaning "everything ok" and if the pulses ever _stop_ coming (or if the emergency button is pressed), secondary arduino performs the E-stop.  If primary arduino has any chance of getting hung or in some other bad state (perhaps likely if it's under heavy development) the secondary arduino E-stop feature is still assured to be intact.  If the primary arduino loses its mind, that's the worst time for the emergency stop button to quit working.

**Comment by Bumblefuck** [comment]
Very clever! Yes!

**Comment by Bumblefuck** [comment]
And visa versa... both units should be capable of triggering e stop if
either unit stops pinging. But I still think the panic button should just
kill all power. It' s not inconceivable that both units would crap out in
tandem.

**Comment by DanNixon** [comment]
@vector76 This could be done using the watchdog timer, there is really no need for a second arduino.

This approach protects against both hardware and software faults, two devices running identical code are vulnerable to the same software issues.

**Comment by DanNixon** [comment]
The original issue was a significant oversight and is fixed in the referenced PR.

**Comment by googolp** [comment]
Thank you @DanNixon.
